-- MySQL Script generated by MySQL Workbench
-- Sat May 13 11:41:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `idEditora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEditora`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`livro` (
  `idLivro` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `anoPublicacao` DATE NOT NULL,
  `isbn` INT UNSIGNED NOT NULL,
  `editora_idEditora` INT NOT NULL,
  PRIMARY KEY (`idLivro`),
  INDEX `fk_livro_editora_idx` (`editora_idEditora` ASC) ,
  CONSTRAINT `fk_livro_editora`
    FOREIGN KEY (`editora_idEditora`)
    REFERENCES `biblioteca`.`editora` (`idEditora`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `idAutor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAutor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`autorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`autorias` (
  `livro_idLivro` INT NOT NULL,
  `autor_idAutor` INT NOT NULL,
  PRIMARY KEY (`livro_idLivro`, `autor_idAutor`),
  INDEX `fk_livro_has_autor_autor1_idx` (`autor_idAutor` ASC) ,
  INDEX `fk_livro_has_autor_livro1_idx` (`livro_idLivro` ASC) ,
  CONSTRAINT `fk_livro_has_autor_livro1`
    FOREIGN KEY (`livro_idLivro`)
    REFERENCES `biblioteca`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_livro_has_autor_autor1`
    FOREIGN KEY (`autor_idAutor`)
    REFERENCES `biblioteca`.`autor` (`idAutor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `usuario_idUsuario` INT NOT NULL,
  `livro_idLivro` INT NOT NULL,
  `dataInicio` DATETIME NOT NULL,
  `dataPrevisaoDevolucao` DATETIME NOT NULL,
  `dataDevolucao` DATETIME NULL,
  PRIMARY KEY (`usuario_idUsuario`, `livro_idLivro`, `dataInicio`),
  INDEX `fk_usuario_has_livro_livro1_idx` (`livro_idLivro` ASC) ,
  INDEX `fk_usuario_has_livro_usuario1_idx` (`usuario_idUsuario` ASC) ,
  CONSTRAINT `fk_usuario_has_livro_usuario1`
    FOREIGN KEY (`usuario_idUsuario`)
    REFERENCES `biblioteca`.`usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_livro_livro1`
    FOREIGN KEY (`livro_idLivro`)
    REFERENCES `biblioteca`.`livro` (`idLivro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;